"""Adversarial-mutation calibration for the per-skill scoring grader.

Periodic (pre-flight or weekly) calibration that injects a small set of known
defects into a target SKILL.md, scores each defective copy against the current
grader, and computes the fraction of mutations that produced a score drop
relative to the baseline (the "catch rate"). A grader whose catch rate is
below the configured threshold cannot discriminate defective from baseline on
this skill, and the calling /skill-iterate Phase 0 pre-flight should defect-park
the skill via the :data:`GRADER_BROKEN_CRASH_CLASS` sub-class rather than enter
the iteration loop and burn budget against a broken signal.

The mechanism is the runtime/grader-targeted counterpart to the storage-time
golden-bad verification gate in ``generate_bad_examples.py`` — see
``docs/investigations/skill-iterate-hill-climbing/06-adversarial-mutation-grader-discrimination-tests.md``
for the design rationale. The mutations land in this module rather than being
generated by an LLM so calibration is deterministic given a seed and stays
cheap (no sub-agent dispatch needed for the mutation step itself).

CLI:
    python adversarial_calibration.py <skill-name>
    python adversarial_calibration.py --skill <skill-name>
    python adversarial_calibration.py --fleet [--batch-size N]
    python adversarial_calibration.py --num-mutations N
    python adversarial_calibration.py --threshold 0.70
    python adversarial_calibration.py --seed <int>

JSON summary is written to stdout (machine-consumed by orchestrators);
human-readable progress is written to stderr.

Pure-Python / stdlib only; the scoring function is dependency-injected so unit
tests do not require a live LLM grader and the CLI can be wired to either the
structural-only fallback or the full composite procedure depending on operator
preference.
"""

from __future__ import annotations

import argparse
import json
import random
import re
import sys
from pathlib import Path
from typing import Any, Callable

# --- Constants ---------------------------------------------------------------

# Crash sub-class name emitted when a calibration run's catch rate falls below
# the configured threshold. /skill-iterate Phase 0 pre-flight maps this to a
# defect-park (autonomy-contract clause 1 / clause 3 style) rather than entering
# the iteration loop. Mirrors the shape of GRADER_SYCOPHANCY_CRASH_CLASS in
# ``_shared/score_skill_composite.py``.
GRADER_BROKEN_CRASH_CLASS: str = "grader-broken-for-skill"

# Default fraction of mutations the grader must "catch" (score strictly lower
# than baseline) for calibration to pass. Per plan §5 New Components.
DEFAULT_CATCH_RATE_THRESHOLD: float = 0.70

# Default number of mutations to enumerate per calibration run. Investigation
# file 06 §How to apply says 3-5 covers the major defect-type axes; we pick 10
# as a default so the fleet calibration has enough samples for a stable catch
# rate even when some kinds are not applicable to a given SKILL.md.
DEFAULT_NUM_MUTATIONS: int = 10

# Default fleet batch size — mirrors generate_bad_examples.py's convention so
# operators see consistent flag behavior across the skill-iterate tooling.
DEFAULT_FLEET_BATCH_SIZE: int = 3


# Deterministic, well-defined defects to inject. The order is intentional:
# enumerate_mutations cycles through kinds in this order until ``num`` is
# reached, so the first N kinds are the ones a small budget probes first.
MUTATION_KINDS: list[str] = [
    "delete_required_bullet",
    "paraphrase_heading",
    "remove_code_fence",
    "swap_must_with_should",
    "delete_section",
    "duplicate_paragraph",
    "remove_leading_imperative",
    "remove_constraint_line",
    "add_trailing_garbage",
    "shuffle_steps",
]

# Workspace layout: <workspace>/.claude/skills/<skill-name>/SKILL.md.
# This file lives at .claude/skills/skill-iterate/scripts/adversarial_calibration.py,
# so parents[2] is .claude/skills/ (the skills root) and parents[4] is the
# workspace root. Mirrors the canonical pattern in
# ``generate_bad_examples.py``; tests in both modules pin this invariant via
# ``test_skills_root_resolves_to_real_directory``.
_SKILLS_ROOT: Path = Path(__file__).resolve().parents[2]
_WORKSPACE_ROOT: Path = _SKILLS_ROOT.parent.parent

# Marker appended by _mutate_add_trailing_garbage so tests can assert presence.
_TRAILING_GARBAGE_MARKER: str = (
    "<!-- adversarial_calibration: trailing-garbage marker -->"
)

# Imperative verbs whose leading occurrence at the start of a procedure step we
# strip in _mutate_remove_leading_imperative. Kept lowercase for case-insensitive
# matching; the verb removal preserves the surrounding text verbatim otherwise.
_LEADING_IMPERATIVES: frozenset[str] = frozenset(
    {
        "use",
        "write",
        "run",
        "avoid",
        "add",
        "remove",
        "do",
        "check",
        "verify",
        "set",
        "read",
        "call",
        "create",
        "delete",
        "update",
        "replace",
        "prefer",
        "ensure",
        "always",
        "never",
        "skip",
        "apply",
        "edit",
        "open",
        "close",
        "save",
        "commit",
        "push",
        "pull",
        "fetch",
        "build",
        "test",
        "confirm",
        "document",
        "note",
        "pass",
        "return",
        "stop",
        "start",
        "halt",
        "continue",
        "mark",
        "tag",
        "pin",
        "default",
    }
)

# Words / phrases the constraint-removal mutation looks for. Word-boundary
# regex match with re.IGNORECASE; one match anywhere on a line marks that line
# for deletion. Lowercase-only entries — case is handled by IGNORECASE on the
# compiled pattern. Word boundaries (``\b``) prevent false positives like
# "Neverending story", "I love mustard", "required Skittles".
_CONSTRAINT_MARKERS: frozenset[str] = frozenset(
    {
        "must not",
        "do not",
        "required",
        "never",
        "must",
    }
)

# Compiled once at module load so per-line scanning in _mutate_remove_constraint_line
# is cheap. Order the alternation longest-first so "must not" matches before
# "must" — both flag the same line for deletion, but longest-first is safer if
# the markers ever get extended.
_CONSTRAINT_MARKER_RE = re.compile(
    r"\b(?:"
    + "|".join(
        re.escape(marker)
        for marker in sorted(_CONSTRAINT_MARKERS, key=len, reverse=True)
    )
    + r")\b",
    re.IGNORECASE,
)


# --- Exceptions --------------------------------------------------------------


class MutationNotApplicable(Exception):
    """Raised when a mutation kind cannot be applied to a given SKILL.md.

    Examples: ``remove_code_fence`` against a SKILL.md with no fenced blocks,
    ``paraphrase_heading`` against a SKILL.md with no headings. Callers (notably
    :func:`enumerate_mutations`) catch this exception and skip the kind rather
    than aborting the calibration run.
    """


# --- Heading + structural helpers --------------------------------------------

_HEADING_RE = re.compile(r"^(#{1,6})\s+(.*?)\s*$")
_FENCE_RE = re.compile(r"^(\s{0,3})(`{3,})(\s*)(\S*)?\s*$")
_LIST_BULLET_RE = re.compile(r"^(\s*)- \*\*([^*]+):\*\*")
_NUMBERED_STEP_RE = re.compile(r"^(\s*)(\d+)\.\s+(.*)$")


def _split_lines_preserving(text: str) -> list[str]:
    """splitlines() preserving the round-trip via ``\\n``.join(...).

    Documented helper so the mutation implementations all use the same
    line-splitting convention; mixing splitlines() shapes between mutators can
    silently drop a trailing newline.
    """
    return text.splitlines()


def _join_lines(lines: list[str], original: str) -> str:
    """Re-join mutated lines, preserving trailing newline iff original had one."""
    result = "\n".join(lines)
    if original.endswith("\n") and not result.endswith("\n"):
        result += "\n"
    return result


# --- Per-mutation implementations -------------------------------------------


def _mutate_delete_required_bullet(skill_md: str, rng: random.Random) -> str:
    """Delete one ``- **Field:** ...`` style list bullet.

    These are load-bearing because /repo-sync and /build-step look for them
    (see workspace memory feedback_repo_sync_bulk_fill_bullet_style). Removing
    one should be a real degradation to a competent grader.
    """
    lines = _split_lines_preserving(skill_md)
    candidates = [i for i, line in enumerate(lines) if _LIST_BULLET_RE.match(line)]
    if not candidates:
        raise MutationNotApplicable("no '- **Field:** ...' bullets found")
    idx = rng.choice(candidates)
    mutated = lines[:idx] + lines[idx + 1 :]
    return _join_lines(mutated, skill_md)


def _mutate_paraphrase_heading(skill_md: str, rng: random.Random) -> str:
    """Replace one heading's text with a paraphrased variant.

    The mutation deliberately keeps the heading level intact (so structural-
    depth metrics do not flip) but changes the semantic content — a grader
    that anchors on heading text (e.g. required-sections detector) should
    notice the change.
    """
    lines = _split_lines_preserving(skill_md)
    heading_indices: list[int] = []
    for i, line in enumerate(lines):
        m = _HEADING_RE.match(line)
        if m:
            heading_indices.append(i)
    if not heading_indices:
        raise MutationNotApplicable("no headings found")
    idx = rng.choice(heading_indices)
    m = _HEADING_RE.match(lines[idx])
    assert m is not None  # validated above
    prefix = m.group(1)
    title = m.group(2)
    paraphrased = f"Renamed Section ({title[::-1]})"
    lines[idx] = f"{prefix} {paraphrased}"
    return _join_lines(lines, skill_md)


def _mutate_remove_code_fence(skill_md: str, rng: random.Random) -> str:
    """Remove the OPENING fence of a code block, breaking the block boundary.

    This trips the code_fence_balance structural metric (unbalanced fence) and
    causes the body of the block to render as ordinary text — a grader looking
    at fenced examples should notice the breakage.
    """
    lines = _split_lines_preserving(skill_md)
    open_fence_indices: list[int] = []
    in_fence = False
    for i, line in enumerate(lines):
        if _FENCE_RE.match(line):
            if not in_fence:
                open_fence_indices.append(i)
            in_fence = not in_fence
    if not open_fence_indices:
        raise MutationNotApplicable("no code fences found")
    idx = rng.choice(open_fence_indices)
    mutated = lines[:idx] + lines[idx + 1 :]
    return _join_lines(mutated, skill_md)


def _mutate_swap_must_with_should(skill_md: str, rng: random.Random) -> str:
    """Replace ONE occurrence of MUST/must with should — a real rule-weakening.

    Preserves case context where possible: ``MUST`` → ``should`` (downgrade
    capitalized rules to plain word), ``must`` → ``should`` (lowercase variant).
    """
    pattern = re.compile(r"\b(MUST|must|Must)\b")
    matches = list(pattern.finditer(skill_md))
    if not matches:
        raise MutationNotApplicable("no 'MUST' / 'must' occurrences found")
    m = rng.choice(matches)
    matched = m.group(0)
    replacement = "should" if matched.islower() or matched.isupper() else "Should"
    return skill_md[: m.start()] + replacement + skill_md[m.end() :]


def _mutate_delete_section(skill_md: str, rng: random.Random) -> str:
    """Delete one ## or ### section (heading + body up to the next heading).

    Picks a non-top-level heading (depth >= 2) and removes from that heading
    through (but excluding) the next heading of equal-or-shallower depth.
    """
    lines = _split_lines_preserving(skill_md)
    candidates: list[tuple[int, int]] = []
    for i, line in enumerate(lines):
        m = _HEADING_RE.match(line)
        if not m:
            continue
        depth = len(m.group(1))
        if depth < 2:
            continue
        # Find the end of this section: next heading at depth <= this one.
        end = len(lines)
        for j in range(i + 1, len(lines)):
            m2 = _HEADING_RE.match(lines[j])
            if m2 and len(m2.group(1)) <= depth:
                end = j
                break
        candidates.append((i, end))
    if not candidates:
        raise MutationNotApplicable("no deletable ## / ### sections found")
    start, end = rng.choice(candidates)
    mutated = lines[:start] + lines[end:]
    return _join_lines(mutated, skill_md)


def _mutate_duplicate_paragraph(skill_md: str, rng: random.Random) -> str:
    """Pick a non-empty paragraph and insert a verbatim copy two lines below.

    A paragraph is a run of non-blank lines bordered by blank lines (or BOF/EOF).
    Duplicating it introduces a real redundancy a careful grader should flag.
    """
    lines = _split_lines_preserving(skill_md)
    paragraphs: list[tuple[int, int]] = []  # (start, end-exclusive)
    cursor = 0
    while cursor < len(lines):
        # Skip blanks
        while cursor < len(lines) and not lines[cursor].strip():
            cursor += 1
        start = cursor
        while cursor < len(lines) and lines[cursor].strip():
            # Only consider plain-prose paragraphs (skip headings, list lines,
            # fence lines, indented code) so the duplicate is itself parseable.
            if (
                _HEADING_RE.match(lines[cursor])
                or _FENCE_RE.match(lines[cursor])
                or lines[cursor].lstrip().startswith(("-", "*", "+", ">"))
                or lines[cursor].startswith("    ")
            ):
                start = -1  # disqualify this paragraph
            cursor += 1
        if start >= 0 and cursor > start:
            paragraphs.append((start, cursor))
    if not paragraphs:
        raise MutationNotApplicable("no plain-prose paragraphs found")
    start, end = rng.choice(paragraphs)
    paragraph_lines = lines[start:end]
    # Insert the duplicate two lines below the paragraph end (creating one blank
    # line + duplicate). Clamp to end of file.
    insert_at = min(end + 1, len(lines))
    mutated = lines[:insert_at] + paragraph_lines + lines[insert_at:]
    return _join_lines(mutated, skill_md)


def _mutate_remove_leading_imperative(skill_md: str, rng: random.Random) -> str:
    """Strip the leading imperative verb from one numbered procedure step.

    Targets `1. Verb the thing.` style lines; removes ``Verb `` and capitalizes
    the next word. Degrades the rules-to-rationale ratio metric and weakens
    the procedural specificity a grader should notice.
    """
    lines = _split_lines_preserving(skill_md)
    candidates: list[int] = []
    for i, line in enumerate(lines):
        m = _NUMBERED_STEP_RE.match(line)
        if not m:
            continue
        body = m.group(3)
        first_word_match = re.match(r"^([A-Za-z']+)\b", body)
        if (
            first_word_match
            and first_word_match.group(1).lower() in _LEADING_IMPERATIVES
        ):
            candidates.append(i)
    if not candidates:
        raise MutationNotApplicable(
            "no numbered steps starting with an imperative verb found"
        )
    idx = rng.choice(candidates)
    m = _NUMBERED_STEP_RE.match(lines[idx])
    assert m is not None
    indent, number, body = m.group(1), m.group(2), m.group(3)
    # Strip leading verb + the single space after it. Capitalize the remainder.
    stripped = re.sub(r"^[A-Za-z']+\s+", "", body, count=1)
    if stripped:
        stripped = stripped[0].upper() + stripped[1:]
    lines[idx] = f"{indent}{number}. {stripped}"
    return _join_lines(lines, skill_md)


def _mutate_remove_constraint_line(skill_md: str, rng: random.Random) -> str:
    """Delete one line containing a load-bearing constraint marker.

    Markers: ``must not``, ``do not``, ``REQUIRED``, ``never``, ``MUST``, etc.
    Removing such a line lifts a real rule and a competent grader should flag
    the regression.

    Matching is word-boundary + case-insensitive (``\\b<marker>\\b`` with
    ``re.IGNORECASE``) so non-constraint lines that merely contain the marker
    as a substring — "I love mustard", "Neverending story", "required Skittles"
    — are NOT marked for deletion.
    """
    lines = _split_lines_preserving(skill_md)
    candidates: list[int] = []
    for i, line in enumerate(lines):
        # Skip headings (we don't want to delete a heading line via this
        # mutation; that's the delete_section mutator's job).
        if _HEADING_RE.match(line):
            continue
        if _CONSTRAINT_MARKER_RE.search(line):
            candidates.append(i)
    if not candidates:
        raise MutationNotApplicable("no constraint-bearing lines found")
    idx = rng.choice(candidates)
    mutated = lines[:idx] + lines[idx + 1 :]
    return _join_lines(mutated, skill_md)


def _mutate_add_trailing_garbage(skill_md: str, _rng: random.Random) -> str:
    """Append ~3 lines of off-topic markdown at the end of the file.

    Always applicable. Tagged with :data:`_TRAILING_GARBAGE_MARKER` so tests
    can assert the marker appears in the mutated output.
    """
    garbage = (
        "\n"
        f"{_TRAILING_GARBAGE_MARKER}\n"
        "## Unrelated Appendix\n"
        "\n"
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. This trailing\n"
        "garbage block is unrelated to the skill above and should be flagged as\n"
        "such by any competent grader.\n"
    )
    if skill_md.endswith("\n"):
        return skill_md + garbage.lstrip("\n")
    return skill_md + garbage


def _mutate_shuffle_steps(skill_md: str, rng: random.Random) -> str:
    """Randomly reorder the numbered items of one ## Steps / ## Procedure section.

    Finds a ``## Steps`` or ``## Procedure`` heading (or any sibling) whose body
    begins with numbered list items; shuffles those items in place. Renumbers
    to keep ``1.``, ``2.``, ``3.`` sequential so the document still parses.
    """
    lines = _split_lines_preserving(skill_md)
    # Find candidate sections: any heading whose body has 2+ numbered items in
    # an unbroken run (separated only by blank lines).
    candidates: list[
        tuple[int, int, list[int]]
    ] = []  # (heading_i, end_i, step_indices)
    for i, line in enumerate(lines):
        m = _HEADING_RE.match(line)
        if not m:
            continue
        depth = len(m.group(1))
        # Find next heading of equal-or-shallower depth.
        section_end = len(lines)
        for j in range(i + 1, len(lines)):
            m2 = _HEADING_RE.match(lines[j])
            if m2 and len(m2.group(1)) <= depth:
                section_end = j
                break
        step_indices = [
            k for k in range(i + 1, section_end) if _NUMBERED_STEP_RE.match(lines[k])
        ]
        if len(step_indices) >= 2:
            candidates.append((i, section_end, step_indices))
    if not candidates:
        raise MutationNotApplicable(
            "no numbered-step sections (2+ items) found to shuffle"
        )
    _heading_i, _section_end, step_indices = rng.choice(candidates)

    # Extract step lines, shuffle, ensure the order actually changed (small
    # sections of 2 items have a 50% same-order roll; loop until different).
    original = [lines[k] for k in step_indices]
    shuffled = list(original)
    if len(original) >= 2:
        for _ in range(8):
            rng.shuffle(shuffled)
            if shuffled != original:
                break
        else:
            # Two-element list that kept rolling identical: force a swap.
            shuffled[0], shuffled[-1] = shuffled[-1], shuffled[0]

    # Renumber to 1., 2., 3., ... preserving each line's body verbatim.
    out_lines = list(lines)
    for new_num, (target_idx, source_line) in enumerate(
        zip(step_indices, shuffled), start=1
    ):
        m = _NUMBERED_STEP_RE.match(source_line)
        assert m is not None
        indent = m.group(1)
        body = m.group(3)
        out_lines[target_idx] = f"{indent}{new_num}. {body}"

    return _join_lines(out_lines, skill_md)


# Dispatch table: kind -> mutator. Centralized so apply_mutation has one place
# to look up rather than a long if/elif chain.
_MUTATORS: dict[str, Callable[[str, random.Random], str]] = {
    "delete_required_bullet": _mutate_delete_required_bullet,
    "paraphrase_heading": _mutate_paraphrase_heading,
    "remove_code_fence": _mutate_remove_code_fence,
    "swap_must_with_should": _mutate_swap_must_with_should,
    "delete_section": _mutate_delete_section,
    "duplicate_paragraph": _mutate_duplicate_paragraph,
    "remove_leading_imperative": _mutate_remove_leading_imperative,
    "remove_constraint_line": _mutate_remove_constraint_line,
    "add_trailing_garbage": _mutate_add_trailing_garbage,
    "shuffle_steps": _mutate_shuffle_steps,
}

assert set(_MUTATORS.keys()) == set(MUTATION_KINDS), (
    "MUTATION_KINDS and _MUTATORS dispatch table drifted out of sync"
)


# --- Public mutation API ----------------------------------------------------


def apply_mutation(
    skill_md: str,
    kind: str,
    rng: random.Random | None = None,
) -> str:
    """Apply one mutation of ``kind`` to ``skill_md`` and return the result.

    Pure function — never reads or writes the filesystem. ``rng`` is injectable
    for reproducibility; when ``None``, a fresh unseeded ``random.Random()`` is
    used (non-reproducible).

    Raises:
        ValueError: ``kind`` is not in :data:`MUTATION_KINDS`.
        MutationNotApplicable: the SKILL.md lacks the target element (e.g.
            ``remove_code_fence`` on a SKILL.md with no fences).
    """
    if kind not in _MUTATORS:
        raise ValueError(
            f"unknown mutation kind {kind!r}; must be one of {sorted(MUTATION_KINDS)}"
        )
    actual_rng = rng if rng is not None else random.Random()
    return _MUTATORS[kind](skill_md, actual_rng)


def enumerate_mutations(
    skill_md: str,
    num: int = DEFAULT_NUM_MUTATIONS,
    rng: random.Random | None = None,
) -> list[tuple[str, str]]:
    """Generate up to ``num`` ``(kind, mutated_content)`` pairs.

    Cycles through :data:`MUTATION_KINDS` in declared order, skipping any kind
    that raises :class:`MutationNotApplicable` for this SKILL.md. Stops when
    ``num`` pairs have been collected OR all kinds have been tried (whichever
    first).

    The order of yielded pairs follows :data:`MUTATION_KINDS` deterministically
    when ``rng`` is seeded; only the per-mutation internal randomness (which
    bullet, which heading, etc.) is rng-driven.
    """
    if num < 0:
        raise ValueError(f"num must be >= 0; got {num}")
    actual_rng = rng if rng is not None else random.Random()
    out: list[tuple[str, str]] = []
    for kind in MUTATION_KINDS:
        if len(out) >= num:
            break
        try:
            mutated = apply_mutation(skill_md, kind, actual_rng)
        except MutationNotApplicable:
            continue
        out.append((kind, mutated))
    return out


# --- Calibration orchestration ----------------------------------------------


def calibrate_skill(
    skill_dir: Path,
    score_fn: Callable[..., float],
    num_mutations: int = DEFAULT_NUM_MUTATIONS,
    threshold: float = DEFAULT_CATCH_RATE_THRESHOLD,
    rng: random.Random | None = None,
) -> dict[str, Any]:
    """Calibrate the grader against ``num_mutations`` known defects in this skill.

    Reads ``<skill_dir>/SKILL.md`` as the baseline. Generates up to
    ``num_mutations`` mutations via :func:`enumerate_mutations`. Scores the
    baseline + every mutation via the injected ``score_fn``. A mutation is
    "caught" if its score is STRICTLY less than the baseline score.

    ``score_fn`` is a callable that takes ONE positional argument — the SKILL.md
    content as a string — and returns a float in ``[0.0, 1.0]``. Dependency
    injection is mandatory: the production CLI wires this to the structural
    metrics axis or to the full composite procedure; tests pass deterministic
    stubs.

    A ``score_fn`` exception while scoring a mutation is caught and treated as
    "not caught" (a grader that crashes can't discriminate). The baseline score
    must succeed — if ``score_fn`` raises on the baseline, the exception
    propagates so callers see the underlying failure rather than a false-positive
    calibration verdict.

    Returns a dict with the shape documented in the module docstring:

    .. code-block:: python

        {
            "skill": "<skill-name>",
            "baseline_score": float,
            "mutations": [
                {"kind": str, "score": float, "caught": bool, "error": str | None},
                ...
            ],
            "catch_rate": float,           # in [0.0, 1.0]
            "threshold": float,
            "verdict": "ok" | "grader-broken-for-skill",
            "reason": str,
        }
    """
    if not skill_dir.is_dir():
        raise FileNotFoundError(f"skill directory not found: {skill_dir}")
    skill_md_path = skill_dir / "SKILL.md"
    if not skill_md_path.is_file():
        raise FileNotFoundError(f"SKILL.md not found: {skill_md_path}")

    # utf-8-sig strips a leading BOM if present (Win PS 5.1 Set-Content writes
    # one — see workspace memory feedback_set_content_utf8_adds_bom).
    skill_md = skill_md_path.read_text(encoding="utf-8-sig")
    baseline_score = float(score_fn(skill_md))

    mutations = enumerate_mutations(skill_md, num=num_mutations, rng=rng)
    mutation_records: list[dict[str, Any]] = []
    caught = 0
    for kind, mutated in mutations:
        error: str | None = None
        score: float
        try:
            score = float(score_fn(mutated))
        except Exception as exc:  # noqa: BLE001 - any failure → not caught
            score = float("nan")
            error = f"{type(exc).__name__}: {exc}"
        is_caught = (error is None) and (score < baseline_score)
        if is_caught:
            caught += 1
        mutation_records.append(
            {
                "kind": kind,
                "score": score,
                "caught": is_caught,
                "error": error,
            }
        )

    total = len(mutation_records)
    catch_rate = (caught / total) if total > 0 else 0.0
    skill_name = skill_dir.name
    pct = round(catch_rate * 100)
    threshold_pct = round(threshold * 100)
    if catch_rate >= threshold:
        verdict = "ok"
        reason = (
            f"caught {caught}/{total} mutations ({pct}% >= {threshold_pct}%); "
            f"grader discriminates defective from baseline on {skill_name}"
        )
    else:
        verdict = GRADER_BROKEN_CRASH_CLASS
        reason = (
            f"caught {caught}/{total} mutations ({pct}% < {threshold_pct}%); "
            f"grader cannot discriminate defective from baseline on {skill_name}"
        )

    return {
        "skill": skill_name,
        "baseline_score": baseline_score,
        "mutations": mutation_records,
        "catch_rate": catch_rate,
        "threshold": threshold,
        "verdict": verdict,
        "reason": reason,
    }


def calibrate_fleet(
    score_fn: Callable[..., float],
    num_mutations: int = DEFAULT_NUM_MUTATIONS,
    threshold: float = DEFAULT_CATCH_RATE_THRESHOLD,
    rng: random.Random | None = None,
    skills_root: Path | None = None,
) -> dict[str, Any]:
    """Calibrate every auto-discovered scorable skill and aggregate results.

    Reuses ``generate_bad_examples.auto_discover_skills`` so the discovery
    contract (``evals/evals.json`` present, name not prefixed with ``_``) stays
    aligned with the rest of the skill-iterate tooling.

    Per-skill failures (missing SKILL.md, score_fn crash on baseline) are
    captured in the result's ``per_skill`` list under an ``error`` key rather
    than raised — one broken skill must not abort fleet calibration.

    Returns:

    .. code-block:: python

        {
            "fleet": True,
            "summary": {"calibrated": int, "broken": int, "total": int},
            "per_skill": [<calibrate_skill result>, ...],
        }
    """
    # Local import to avoid a heavy module-load chain when callers only need
    # the per-skill API. The eval-setup script lives in a sibling skill dir
    # under .claude/skills/; resolve via _SKILLS_ROOT so the path is correct
    # regardless of cwd.
    eval_setup_dir = _SKILLS_ROOT / "skill-eval-setup" / "scripts"
    if str(eval_setup_dir) not in sys.path:
        sys.path.insert(0, str(eval_setup_dir))
    from generate_bad_examples import auto_discover_skills  # noqa: E402

    root = skills_root if skills_root is not None else _SKILLS_ROOT
    names = auto_discover_skills(skills_root=root)

    per_skill: list[dict[str, Any]] = []
    calibrated = 0
    broken = 0
    for name in names:
        skill_dir = root / name
        try:
            result = calibrate_skill(
                skill_dir,
                score_fn,
                num_mutations=num_mutations,
                threshold=threshold,
                rng=rng,
            )
        except Exception as exc:  # noqa: BLE001 - fleet resilience
            per_skill.append(
                {
                    "skill": name,
                    "error": f"{type(exc).__name__}: {exc}",
                }
            )
            continue
        per_skill.append(result)
        if result["verdict"] == "ok":
            calibrated += 1
        elif result["verdict"] == GRADER_BROKEN_CRASH_CLASS:
            broken += 1

    return {
        "fleet": True,
        "summary": {
            "calibrated": calibrated,
            "broken": broken,
            "total": calibrated + broken,
        },
        "per_skill": per_skill,
    }


# --- Default scoring (structural-only) --------------------------------------


def _default_structural_score_fn(skill_md_content: str) -> float:
    """Default score_fn for the CLI: write content to a temp file + run structural metrics.

    The structural axis is fully deterministic and stdlib-friendly; no LLM
    dispatch is needed. Operators who want the full composite procedure can
    drive ``calibrate_skill`` from Python and inject their own ``score_fn`` —
    the CLI's structural-only mode is a calibration-of-the-grader-floor
    measurement, useful as a smoke check.
    """
    # Local imports to keep the module-level surface focused on calibration.
    import tempfile

    sibling_scripts = Path(__file__).resolve().parent
    if str(sibling_scripts) not in sys.path:
        sys.path.insert(0, str(sibling_scripts))
    from structural_metrics import score_skill as run_structural  # noqa: E402

    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".md", delete=False, encoding="utf-8"
    ) as tmp:
        tmp.write(skill_md_content)
        tmp_path = Path(tmp.name)
    try:
        return float(run_structural(tmp_path).score)
    finally:
        try:
            tmp_path.unlink()
        except OSError:
            pass


# --- CLI ---------------------------------------------------------------------


def _build_argparser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="adversarial_calibration.py",
        description=(
            "Calibrate a per-skill scoring grader by injecting known defects into "
            "SKILL.md, scoring each, and reporting the catch rate. Below the "
            "configured threshold (default 70%) the grader is unfit for this "
            "skill and /skill-iterate Phase 0 should defect-park rather than enter "
            f"the iteration loop ({GRADER_BROKEN_CRASH_CLASS})."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "skill_name_positional",
        nargs="?",
        default=None,
        metavar="<skill-name>",
        help="Skill name (e.g. session-wrap). Alternative to --skill.",
    )
    parser.add_argument(
        "--skill",
        dest="skill_name_flag",
        default=None,
        help="Skill name. Same as the positional argument; provided for explicit-flag callers.",
    )
    parser.add_argument(
        "--fleet",
        action="store_true",
        help="Calibrate every auto-discovered scorable skill.",
    )
    parser.add_argument(
        "--num-mutations",
        type=int,
        default=DEFAULT_NUM_MUTATIONS,
        help=f"Mutations per skill (default: {DEFAULT_NUM_MUTATIONS}).",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=DEFAULT_CATCH_RATE_THRESHOLD,
        help=f"Catch-rate pass threshold (default: {DEFAULT_CATCH_RATE_THRESHOLD}).",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="Random seed for reproducible mutations (default: unseeded).",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = _build_argparser()
    args = parser.parse_args(argv)

    skill_name = args.skill_name_flag or args.skill_name_positional

    if args.fleet and skill_name:
        print(
            "error: --fleet and <skill-name> are mutually exclusive",
            file=sys.stderr,
        )
        return 2
    if not args.fleet and not skill_name:
        parser.print_usage(sys.stderr)
        print(
            "error: provide <skill-name> (or --skill <name>) or use --fleet",
            file=sys.stderr,
        )
        return 2

    rng = random.Random(args.seed) if args.seed is not None else None

    try:
        if args.fleet:
            print(
                f"[adversarial_calibration] fleet mode, num_mutations={args.num_mutations}, "
                f"threshold={args.threshold}, seed={args.seed}",
                file=sys.stderr,
            )
            result = calibrate_fleet(
                _default_structural_score_fn,
                num_mutations=args.num_mutations,
                threshold=args.threshold,
                rng=rng,
            )
            print(
                f"[adversarial_calibration] calibrated={result['summary']['calibrated']} "
                f"broken={result['summary']['broken']} total={result['summary']['total']}",
                file=sys.stderr,
            )
        else:
            skill_dir = _SKILLS_ROOT / skill_name
            print(
                f"[adversarial_calibration] skill={skill_name}, num_mutations={args.num_mutations}, "
                f"threshold={args.threshold}, seed={args.seed}",
                file=sys.stderr,
            )
            result = calibrate_skill(
                skill_dir,
                _default_structural_score_fn,
                num_mutations=args.num_mutations,
                threshold=args.threshold,
                rng=rng,
            )
            print(
                f"[adversarial_calibration] {skill_name}: verdict={result['verdict']} "
                f"catch_rate={result['catch_rate']:.2f}",
                file=sys.stderr,
            )
    except FileNotFoundError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 3

    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
